use_frameworks!

platform :ios, '8.0'

target 'DriverRecordSoundKit_Example' do
  pod 'DriverRecordSoundKit', :path => '../'

  target 'DriverRecordSoundKit_Tests' do
    inherit! :search_paths

    
  end
end
